version: "3.8"

services:

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend


  backend:
    build: ./backend
    container_name: backend-api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


volumes:

  mongo-data:
