name: Full Stack CI/CD

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        run: |
          docker build -t dhanu92/backend ./backend

      - name: Push Backend
        run: |
          docker push dhanu92/backend

      - name: Build Frontend Image
        run: |
          docker build -t dhanu92/frontend ./frontend

      - name: Push Frontend
        run: |
          docker push dhanu92/frontend

# CD PART STARTS HERE

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:

          host: ${{ secrets.EC2_HOST }}

          username: ubuntu

          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            docker pull dhanu92/frontend

            docker pull dhanu92/backend


            docker stop frontend || true
            docker stop backend || true


            docker rm frontend || true
            docker rm backend || true


            docker run -d \
            --name frontend \
            -p 80:80 \
            dhanu92/frontend


            docker run -d \
            --name backend \
            -p 5000:5000 \
            dhanu92/backend
